"""added faceImage migrate #1

Revision ID: 053e693cfe36
Revises: 
Create Date: 2023-11-07 23:37:54.093580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053e693cfe36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faceImage', sa.LargeBinary(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('faceImage')

    # ### end Alembic commands ###
