"""added Courses and Attendance

Revision ID: 40c94fdf79f0
Revises: 053e693cfe36
Create Date: 2023-11-08 04:46:42.637479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c94fdf79f0'
down_revision = '053e693cfe36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=50), nullable=False),
    sa.Column('course_code', sa.String(length=50), nullable=False),
    sa.Column('time_slot', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('attendance_time', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('attendance_id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('faceImage',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('faceImage',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=False)

    op.drop_table('attendance')
    op.drop_table('courses')
    # ### end Alembic commands ###
