"""added last_updated

Revision ID: 476b8b1d0a38
Revises: 5636fa4961c6
Create Date: 2023-12-14 00:07:52.825392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476b8b1d0a38'
down_revision = '5636fa4961c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
